"""
Generate a polished PDF report for Task 1.
"""

from pathlib import Path
import textwrap

import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import pandas as pd
import seaborn as sns


BASE_DIR = Path(__file__).resolve().parent.parent
TASK1_DIR = Path(__file__).resolve().parent
INPUT = TASK1_DIR / 'data' / 'Teen_Mental_Health_Dataset.csv'
OUT_DIR = Path(__file__).resolve().parent / 'outputs'
OUT_DIR.mkdir(exist_ok=True)
OUT_PDF = OUT_DIR / 'analysis_report.pdf'


def title_page(pdf, title, subtitle=None):
    fig = plt.figure(figsize=(11.7, 8.3))
    fig.patch.set_facecolor('#f7f7f7')
    plt.axis('off')
    plt.text(0.5, 0.6, title, ha='center', va='center', fontsize=28, weight='bold')
    if subtitle:
        plt.text(0.5, 0.45, subtitle, ha='center', va='center', fontsize=14)
    plt.text(0.5, 0.25, 'Generated with a simple Python report script', ha='center', va='center', fontsize=10, color='#666')
    pdf.savefig(fig)
    plt.close(fig)


def text_page(pdf, heading, lines):
    fig = plt.figure(figsize=(11.7, 8.3))
    plt.axis('off')
    plt.title(heading, fontsize=18, weight='bold', pad=20)
    wrapped = []
    for line in lines:
        wrapped.extend(textwrap.wrap(line, width=100) or [''])
    plt.text(0.01, 0.98, '\n'.join(wrapped), va='top', fontsize=10, family='monospace')
    pdf.savefig(fig)
    plt.close(fig)


def table_page(pdf, table_df, title='Sample rows'):
    df = table_df.copy()
    if df.shape[1] > 8:
        cols = list(df.columns[:6]) + list(df.columns[-2:])
        df = df[cols]

    fig, ax = plt.subplots(figsize=(11.7, 8.3))
    ax.axis('off')
    ax.set_title(title, fontsize=16, weight='bold')
    table = ax.table(cellText=df.values, colLabels=df.columns, loc='center', cellLoc='center')
    table.auto_set_font_size(False)
    table.set_fontsize(8)
    table.scale(1, 1.5)
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def categorical_charts(pdf, df, columns):
    for column in columns:
        fig, ax = plt.subplots(figsize=(11.7, 6))
        counts = df[column].value_counts(dropna=False)
        sns.barplot(x=counts.values, y=counts.index, ax=ax, color='#4c72b0')
        ax.set_xlabel('Count')
        ax.set_ylabel(column)
        ax.set_title(f'Top counts: {column}')
        pdf.savefig(fig, bbox_inches='tight')
        plt.close(fig)


def numeric_histograms(pdf, df, columns):
    group_size = 4
    for start in range(0, len(columns), group_size):
        subset = columns[start:start + group_size]
        fig, axes = plt.subplots(len(subset), 1, figsize=(11.7, 3 * len(subset)))
        if len(subset) == 1:
            axes = [axes]
        for ax, column in zip(axes, subset):
            sns.histplot(df[column].dropna(), bins=20, ax=ax, color='#4c72b0')
            ax.set_title(column)
        plt.tight_layout()
        pdf.savefig(fig, bbox_inches='tight')
        plt.close(fig)


def main():
    input_file = INPUT
    if not input_file.exists():
        input_file = BASE_DIR / 'Teen_Mental_Health_Dataset.csv'

    if not input_file.exists():
        print(f'Input file not found: {input_file}')
        return

    df = pd.read_csv(input_file)

    with PdfPages(OUT_PDF) as pdf:
        title_page(pdf, 'Task 1 - Teen Mental Health Dataset', f'Dataset: {input_file.name}')

        lines = [f'Rows: {df.shape[0]}', f'Columns: {df.shape[1]}', '']
        lines.append('Columns and dtypes:')
        for column, dtype in df.dtypes.items():
            lines.append(f'- {column}: {dtype}')
        text_page(pdf, 'Dataset summary', lines)

        table_page(pdf, df.head(10), title='First 10 rows')

        cat_cols = [c for c in df.columns if pd.api.types.is_string_dtype(df[c]) or str(df[c].dtype) == 'category']
        preferred = ['gender', 'platform_usage', 'social_interaction_level']
        ordered = [c for c in preferred if c in cat_cols] + [c for c in cat_cols if c not in preferred]
        categorical_charts(pdf, df, ordered[:6])

        num_cols = df.select_dtypes(include=['number']).columns.tolist()
        numeric_histograms(pdf, df, num_cols)

        report_path = OUT_DIR / 'simple_report.txt'
        if report_path.exists():
            text_page(pdf, 'Simple report', report_path.read_text(encoding='utf8').splitlines())

        text_page(pdf, 'End of report', ['Generated by Task-1/generate_report.py', f'File: {OUT_PDF.name}'])

    print(f'PDF report written to: {OUT_PDF}')


if __name__ == '__main__':
    main()
